### ISSUE TITLE
Add Linux build to conda cloud with changes from PR #145

### ISSUE THREAD

**Issue by kberryUSGS** [conda-forge/qt-feedstock#153]
Issue: Could a Linux build that includes the changes merged in PR #145 be uploaded to Anaconda Cloud? I only see a Mac build at https://anaconda.org/conda-forge/qt/files.

**Comment by isuruf** [comment]
Linux build segfaults at the test stage.

**Comment by ccordoba12** [comment]
It's very hard to properly test Qt builds on the conda-forge docker image. @isuruf, could you verify if the build is working when installing it under a regular desktop session?

**Comment by isuruf** [comment]
It worked okay for the last 3 builds I made on the same setup, but the latest master segfaults.

**Comment by Kelvinrr** [comment]
@isuruf @ccordoba12 Bumping this, any updates on getting this uploaded for Linux? We are still dependent on a snowflake Qt build and would love to switch to this recipe.

**Comment by isuruf** [comment]
Sorry, no updates. It still segfaults. It would be helpful if you could try and fix the issue.

**Comment by Kelvinrr** [comment]
@isuruf I made an attempt the other day to poke around and see if I can get a local copy of Qt testing correctly, but using the build_locally.py script for linux, it seems to fail on build:

```shell
 File "/opt/conda/lib/python3.7/site-packages/conda/models/match_spec.py", line 506, in _merge
   final = this_component.merge(that_component)
 File "/opt/conda/lib/python3.7/site-packages/conda/models/match_spec.py", line 759, in merge
   % (self.raw_value, other.raw_value))
ValueError: Incompatible component merge:
 - 'h5a48372_1011_cpython'
 - 'he5300dc_6_cpython'
Traceback (most recent call last):
 File "build-locally.py", line 63, in <module>
   main()
 File "build-locally.py", line 59, in main
   run_docker_build(ns)
 File "build-locally.py", line 19, in run_docker_build
   subprocess.check_call([script])
 File "/home/krodriguez/anaconda3/lib/python3.7/subprocess.py", line 341, in check_call
   raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.scripts/run_docker_build.sh']' returned non-zero exit status 1.
```
Any idea why this is happening? Am I missing something otherwise obvious our should I make a separate issue about the build failure.

**Comment by isuruf** [comment]
Can you try the following diff?
```
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index 20700b5..62b25e1 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -117,7 +117,7 @@ requirements:
     - pkg-config                         # [linux]
     - make                               # [unix]
     # Probably only needed for WebEngine
-    - python 2.7*
+    - python *
     - ninja
     - ruby >=2.5                         # [linux]
     - bison                              # [linux]
@@ -133,7 +133,9 @@ requirements:
     # Otherwise build and host might end up with two different versions
     # If they do, merge_build_host will fail.
     - readline                           # [linux]
+    - ld_impl_linux-64 >=2.34            # [linux]
   host:
+    - ld_impl_linux-64 >=2.34            # [linux]
     # For pkg-config gl, fontconfig + freetype
     - pthread-stubs                      # [linux]
     - dbus                               # [linux]
```
